development:
  clients:
    default:
      database: shopselfcheckout_cart
      hosts:
        - localhost:27017
production:
  clients:
    default:
      database: shopselfcheckout_cart
      hosts:
        - mongodb:27017
